// This file is generated by Slice Machine. Update with care!

import Formulario from './Formulario';
import Hero from './Hero';
import Image from './Image';
import TextEdito from './TextEdito';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Formulario,
	Hero,
	Image,
	TextEdito,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	formulario: Formulario,
	hero: Hero,
	image: Image,
	text_edito: TextEdito,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
